language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    # - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

script:
    ./gradlew clean assemble --stacktrace

jdk:
    - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false
  slack:
    secure: XUQ4lmT94T4mkvhjdmWka+uYYEmP7Oz/Q68d8wVe+dHsgs0IUd6NvB4dGLsQ7CnE/LS++vOrb5J/SMbL8KF28tVnsRWhI+eNoaI3KPjUeuaaX8ZsZRodQwIXtWgIRLetfiPD7mDmL+deHXE13SG0sCTO6dkV3FogJb0/v+u0MxMxuIVGvC1X/lMpYxfkinAuaZ0u0UbmTtB4qW9hbQUvPJCUreNY6h1SxVrPn9KarcTcg5uDnXyhQID4rbPmf+xPRBmkkQlWtVBxVZ3pbR3JxV8GwH1Rjh08AYh8LD5Ww1FYXaS4QDukFd5jAtSGuXUqDfyMFwURQS9sdnHT5rDu8rAqPtdnp49tfqHA96zEjWKDQFlS3pkkfjdOw4sftCP381ZqDW2xojpAy/n9+V5dPu6Vo1m1lf6bHo40Vdn9AKTIJfVSStHTWpN6JfeFLcng7utBZv9iDeYF82zcgbL2x3JPZkkg7w+t5922cwrrUdjsUqm6tYss01n+jXEHnhp37BC6P0x7LvD2mZILC69O5MAysBQx52M2UDXa3mGPjLcyB8IEmp2MU4keR2hgiCJu7xvdP47TTXjd+DKtgqPTZg624Bj+jsZ1xSTpQ5p54qHskjFOTygBFz+p6F8PYb7bomIQIBeVPzyultWPPT7ajad4uUDIRK2E7xIm4JIUskM=


sudo: false
